import { useEffect, useState } from 'react';
import { Loader } from 'lucide-react';
import { useFarm } from '../hooks/useFarm';
import { timelineApi } from '../api/client';
import type { TimelineEvent } from '../types';
import clsx from 'clsx';

export default function Timeline() {
  const { farm, loadDemoFarm } = useFarm();
  const [events, setEvents] = useState<TimelineEvent[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!farm) {
      loadDemoFarm().then(() => {});
    } else {
      fetchTimeline();
    }
  }, [farm?.farm_id]);

  const fetchTimeline = async () => {
    if (!farm?.farm_id) return;
    setLoading(true);
    try {
      const data = await timelineApi.get(farm.farm_id);
      setEvents(data);
    } catch {
      // use demo events on error
      setEvents(getDemoEvents());
    } finally {
      setLoading(false);
    }
  };

  const getDemoEvents = (): TimelineEvent[] => [
    { id: 1, event_type: 'planting', description: 'Tomato seeds planted in prepared beds', icon: '🌱', date: new Date(Date.now() - 45 * 86400000).toISOString().split('T')[0], day_number: 1, is_today: false },
    { id: 2, event_type: 'irrigation', description: 'First drip irrigation cycle started', icon: '💧', date: new Date(Date.now() - 25 * 86400000).toISOString().split('T')[0], day_number: 20, is_today: false },
    { id: 3, event_type: 'weather', description: 'Rainfall detected — 18mm received', icon: '🌦', date: new Date(Date.now() - 13 * 86400000).toISOString().split('T')[0], day_number: 32, is_today: false },
    { id: 4, event_type: 'health_check', description: 'Crop health inspection performed', icon: '🐛', date: new Date().toISOString().split('T')[0], day_number: 45, is_today: true },
    { id: 5, event_type: 'ai_recommendation', description: 'AI recommendation generated by AgriSaarthi', icon: '🤖', date: new Date().toISOString().split('T')[0], day_number: 45, is_today: true },
  ];

  const displayEvents = events.length > 0 ? events : getDemoEvents();

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader className="w-8 h-8 text-forest-600 animate-spin" />
        <span className="ml-3 text-gray-600">Loading timeline…</span>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">📅 Farm Timeline</h1>
        <p className="text-gray-500 mt-1">
          {farm ? `${farm.crop_name} · Started ${farm.crop_age_days} days ago` : 'Crop history and events'}
        </p>
      </div>

      {/* Stats */}
      {farm && (
        <div className="grid grid-cols-3 gap-4">
          <div className="card p-4 text-center">
            <div className="text-2xl font-bold text-forest-600">{farm.crop_age_days}</div>
            <div className="text-xs text-gray-500 mt-0.5">Days Growing</div>
          </div>
          <div className="card p-4 text-center">
            <div className="text-2xl font-bold text-blue-500">{displayEvents.length}</div>
            <div className="text-xs text-gray-500 mt-0.5">Events Recorded</div>
          </div>
          <div className="card p-4 text-center">
            <div className="text-lg font-bold text-amber-500">{farm.growth_stage}</div>
            <div className="text-xs text-gray-500 mt-0.5">Current Stage</div>
          </div>
        </div>
      )}

      {/* Timeline */}
      <div className="card p-6">
        <h2 className="font-semibold text-gray-800 mb-6">Crop Journey</h2>
        <div className="relative">
          {/* Vertical line */}
          <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-forest-200"></div>

          <div className="space-y-6">
            {displayEvents.map((event, idx) => (
              <div key={event.id} className="flex gap-4 relative">
                {/* Icon circle */}
                <div className={clsx(
                  'w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0 text-xl border-2 z-10',
                  event.is_today
                    ? 'bg-forest-600 border-forest-500 shadow-lg shadow-forest-200'
                    : 'bg-white border-forest-300'
                )}>
                  {event.icon}
                </div>

                {/* Content */}
                <div className={clsx(
                  'flex-1 p-4 rounded-xl border',
                  event.is_today
                    ? 'bg-forest-50 border-forest-200'
                    : 'bg-gray-50 border-gray-200'
                )}>
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <div className={clsx(
                        'font-semibold',
                        event.is_today ? 'text-forest-800' : 'text-gray-800'
                      )}>
                        {event.description}
                      </div>
                      <div className="text-sm text-gray-500 mt-1 flex items-center gap-3">
                        <span>{formatDate(event.date)}</span>
                        {event.day_number && (
                          <span className="text-forest-600 font-medium">Day {event.day_number}</span>
                        )}
                      </div>
                    </div>
                    {event.is_today && (
                      <span className="badge-green text-xs flex-shrink-0">Today</span>
                    )}
                  </div>
                </div>
              </div>
            ))}

            {/* Future milestone */}
            <div className="flex gap-4 relative">
              <div className="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0 text-xl border-2 border-dashed border-gray-300 bg-white z-10 opacity-50">
                🏆
              </div>
              <div className="flex-1 p-4 rounded-xl border border-dashed border-gray-200 bg-white opacity-50">
                <div className="font-semibold text-gray-600">Harvest Time</div>
                <div className="text-sm text-gray-400 mt-1">
                  Expected in ~{Math.max(0, 90 - (farm?.crop_age_days || 45))} days
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Growth stages reference */}
      <div className="card p-5">
        <h3 className="font-semibold text-gray-800 mb-4">Growth Stages Reference</h3>
        <div className="space-y-2">
          {[
            { stage: 'Seedling', range: '0-15 days', icon: '🌱', current: (farm?.crop_age_days || 0) <= 15 },
            { stage: 'Vegetative', range: '15-30 days', icon: '🌿', current: (farm?.crop_age_days || 0) > 15 && (farm?.crop_age_days || 0) <= 30 },
            { stage: 'Flowering', range: '30-60 days', icon: '🌸', current: (farm?.crop_age_days || 0) > 30 && (farm?.crop_age_days || 0) <= 60 },
            { stage: 'Fruiting', range: '60-90 days', icon: '🍅', current: (farm?.crop_age_days || 0) > 60 && (farm?.crop_age_days || 0) <= 90 },
            { stage: 'Harvest', range: '90-120 days', icon: '🏆', current: (farm?.crop_age_days || 0) > 90 },
          ].map(s => (
            <div key={s.stage} className={clsx(
              'flex items-center gap-3 p-2 rounded-lg text-sm',
              s.current ? 'bg-forest-50 border border-forest-200' : ''
            )}>
              <span className="text-lg w-8 text-center">{s.icon}</span>
              <div className="flex-1">
                <span className={clsx('font-medium', s.current ? 'text-forest-800' : 'text-gray-700')}>{s.stage}</span>
                <span className="text-gray-400 ml-2 text-xs">{s.range}</span>
              </div>
              {s.current && <span className="badge-green text-xs">Current</span>}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
