-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Farms table
CREATE TABLE IF NOT EXISTS farms (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255),
    location VARCHAR(255),
    size_acres DECIMAL(10,2),
    soil_type VARCHAR(100),
    irrigation_method VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Crops table
CREATE TABLE IF NOT EXISTS crops (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER REFERENCES farms(id) ON DELETE CASCADE,
    crop_name VARCHAR(100) NOT NULL,
    variety VARCHAR(100),
    planted_date DATE,
    age_days INTEGER DEFAULT 0,
    growth_stage VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Soil records table
CREATE TABLE IF NOT EXISTS soil_records (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER REFERENCES farms(id) ON DELETE CASCADE,
    moisture_percent DECIMAL(5,2),
    ph_level DECIMAL(4,2),
    nitrogen_level VARCHAR(50),
    recorded_at TIMESTAMP DEFAULT NOW()
);

-- Weather records table
CREATE TABLE IF NOT EXISTS weather_records (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER REFERENCES farms(id) ON DELETE CASCADE,
    temperature_celsius DECIMAL(5,2),
    humidity_percent DECIMAL(5,2),
    rain_probability_percent DECIMAL(5,2),
    wind_speed_kmh DECIMAL(6,2),
    rainfall_mm DECIMAL(6,2),
    is_demo BOOLEAN DEFAULT TRUE,
    recorded_at TIMESTAMP DEFAULT NOW()
);

-- Crop health records
CREATE TABLE IF NOT EXISTS crop_health (
    id SERIAL PRIMARY KEY,
    crop_id INTEGER REFERENCES crops(id) ON DELETE CASCADE,
    image_filename VARCHAR(255),
    analysis_result JSONB,
    disease_detected VARCHAR(255),
    confidence_percent DECIMAL(5,2),
    is_demo_analysis BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- AI recommendations table
CREATE TABLE IF NOT EXISTS ai_recommendations (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER REFERENCES farms(id) ON DELETE CASCADE,
    user_query TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    agents_used TEXT[],
    sources TEXT[],
    confidence VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Knowledge documents (RAG source)
CREATE TABLE IF NOT EXISTS knowledge_documents (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Knowledge chunks (RAG vectors)
CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id SERIAL PRIMARY KEY,
    document_id INTEGER REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_text TEXT NOT NULL,
    embedding vector(384),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Agent run logs
CREATE TABLE IF NOT EXISTS agent_runs (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER,
    query TEXT,
    agent_name VARCHAR(100),
    result JSONB,
    duration_ms INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Farm timeline events
CREATE TABLE IF NOT EXISTS farm_timeline (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER REFERENCES farms(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL,
    event_description TEXT NOT NULL,
    event_icon VARCHAR(10),
    event_date DATE NOT NULL,
    day_number INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Seed demo data
INSERT INTO users (name, email) VALUES ('Ramesh', 'ramesh@demo.com') ON CONFLICT DO NOTHING;

INSERT INTO farms (user_id, name, location, size_acres, soil_type, irrigation_method)
VALUES (1, 'Ramesh Farm', 'Belagavi, Karnataka', 2.4, 'Loamy', 'Drip') ON CONFLICT DO NOTHING;

INSERT INTO crops (farm_id, crop_name, planted_date, age_days, growth_stage, is_active)
VALUES (1, 'Tomato', CURRENT_DATE - INTERVAL '45 days', 45, 'Flowering', true) ON CONFLICT DO NOTHING;

INSERT INTO soil_records (farm_id, moisture_percent, ph_level, nitrogen_level)
VALUES (1, 64.0, 6.5, 'Medium');

INSERT INTO weather_records (farm_id, temperature_celsius, humidity_percent, rain_probability_percent, wind_speed_kmh, is_demo)
VALUES (1, 29.0, 75.0, 78.0, 12.0, true);

INSERT INTO farm_timeline (farm_id, event_type, event_description, event_icon, event_date, day_number)
VALUES
(1, 'planting', 'Tomato seeds planted in prepared beds', '🌱', CURRENT_DATE - INTERVAL '45 days', 1),
(1, 'irrigation', 'First drip irrigation cycle started', '💧', CURRENT_DATE - INTERVAL '25 days', 20),
(1, 'weather', 'Rainfall detected – 18mm received', '🌦', CURRENT_DATE - INTERVAL '13 days', 32),
(1, 'health_check', 'Crop health inspection performed', '🐛', CURRENT_DATE, 45),
(1, 'ai_recommendation', 'AI recommendation generated by AgriSaarthi', '🤖', CURRENT_DATE, 45);
